apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  # Имя HPA-ресурса
  name: rental-app-api-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    # Ссылка на Deployment, который масштабируем
    name: rental-app-api
  minReplicas: 2
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70  # При 70% CPU будет поднимать реплики


