version: '3.8'

services:
  fs-broker:
    build:
      context: ..
      dockerfile: fs_subscriber/Dockerfile
    container_name: fs-broker
    command: ["broker"]
    env_file:
      - ../.env
    environment:
      - FS__FASTSTREAM__KAFKA_URL=${FS__FASTSTREAM__KAFKA_URL:-kafka:9092}
      - FS__FASTSTREAM__SUBJECT=${FS__FASTSTREAM__SUBJECT:-user-register}
      - FS__LOGGING__LOG_LEVEL=${FS__LOGGING__LOG_LEVEL:-info}
    volumes:
      - ../fs_subscriber:/app/fs_subscriber
    networks:
      - fs-network
    restart: unless-stopped
    depends_on:
      - kafka

  fs-docs:
    build:
      context: ..
      dockerfile: fs_subscriber/Dockerfile
    container_name: fs-docs
    command: ["docs"]
    env_file:
      - ../.env
    environment:
      - FS__FASTSTREAM__KAFKA_URL=${FS__FASTSTREAM__KAFKA_URL:-kafka:9092}
      - FS__FASTSTREAM__SUBJECT=${FS__FASTSTREAM__SUBJECT:-user-register}
      - FS__LOGGING__LOG_LEVEL=${FS__LOGGING__LOG_LEVEL:-info}
    ports:
      - "8081:8081"
    volumes:
      - ../fs_subscriber:/app/fs_subscriber
    networks:
      - fs-network
    restart: unless-stopped
    depends_on:
      - kafka

  # Kafka для тестирования (если не используется внешний)
  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    ports:
      - "29092:29092"
    networks:
      - fs-network
    depends_on:
      - zookeeper
    restart: unless-stopped

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - fs-network
    restart: unless-stopped

networks:
  fs-network:
    driver: bridge
