"""add domain models: cars, car_photos, orders, deliveries, payments, car_reports, reviews; user relations

Revision ID: 31a91ebf82a8
Revises: 15d90e69db64
Create Date: 2025-08-09 05:15:26.478257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31a91ebf82a8'
down_revision: Union[str, Sequence[str], None] = '15d90e69db64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('car_photos',
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=False),
    sa.Column('is_main', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_car_photos_car_id'), 'car_photos', ['car_id'], unique=False)
    op.create_table('car_reports',
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.Column('report_type', sa.String(length=64), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_car_reports_car_id'), 'car_reports', ['car_id'], unique=False)
    op.create_table('orders',
    sa.Column('customer_name', sa.String(length=128), nullable=False),
    sa.Column('customer_phone', sa.String(length=64), nullable=False),
    sa.Column('customer_email', sa.String(length=128), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'paid', 'processing', 'in_delivery', 'completed', 'canceled', name='order_status', create_type=False), nullable=False),
    sa.Column('payment_method', sa.Enum('cash', 'card', 'loan', 'lease', name='payment_method', create_type=False), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('delivery_address', sa.Text(), nullable=True),
    sa.Column('delivery_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_car_id'), 'orders', ['car_id'], unique=False)
    op.create_index(op.f('ix_orders_user_id'), 'orders', ['user_id'], unique=False)
    op.create_table('reviews',
    sa.Column('customer_name', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(length=1024), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reviews_car_id'), 'reviews', ['car_id'], unique=False)
    op.create_index(op.f('ix_reviews_user_id'), 'reviews', ['user_id'], unique=False)
    op.create_table('deliveries',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'in_progress', 'delivered', 'failed', name='delivery_status', create_type=False), nullable=False),
    sa.Column('tracking_number', sa.String(length=128), nullable=True),
    sa.Column('delivered_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deliveries_order_id'), 'deliveries', ['order_id'], unique=False)
    op.create_table('payments',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('pending', 'paid', 'failed', name='payment_status', create_type=False), nullable=False),
    sa.Column('payment_type', sa.Enum('full', 'installment', 'deposit', name='payment_type',create_type=False), nullable=False),
    sa.Column('transaction_id', sa.String(length=128), nullable=True),
    sa.Column('paid_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_order_id'), 'payments', ['order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_order_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_deliveries_order_id'), table_name='deliveries')
    op.drop_table('deliveries')
    op.drop_index(op.f('ix_reviews_user_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_car_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_orders_user_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_car_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_car_reports_car_id'), table_name='car_reports')
    op.drop_table('car_reports')
    op.drop_index(op.f('ix_car_photos_car_id'), table_name='car_photos')
    op.drop_table('car_photos')
    # ### end Alembic commands ###

    # todo: для ENUM руками-алембик не удаляет
    op.execute("DROP TYPE IF EXISTS order_status CASCADE;")
    op.execute("DROP TYPE IF EXISTS payment_method CASCADE;")
    op.execute("DROP TYPE IF EXISTS delivery_status CASCADE;")
    op.execute("DROP TYPE IF EXISTS payment_status CASCADE;")
    op.execute("DROP TYPE IF EXISTS payment_type CASCADE;")
