targets:
  $default:
    builders:
      swagger_dart_code_generator:
        options:
          input_folder: lib/swagger
          output_folder: lib/generated
          enums_case_sensitive: false
          separate_models: true
          build_only_models: true

